Implements switch graph button for deputies list (wip)
Augora/Augora pull request #388
Opened 2020-11-22 13:23 UTC by goldenivan

CU-94r86m

Cannot change some CSS interactions (hover, cursor) while it's
waiting for feature/page-carte-france styles modifications on
filters

### Description

Cette pull request a pour but l'implémentation d'un bouton de switch de graphe.

2020-11-22 13:23 UTC, KevinBacas commented
Task linked: [CU-94r86m Icône de switch donut <--> histogramme](https://app.clickup.com/t/94r86m)

2020-11-23 11:05 UTC, Narcasung requested changes
Le bouton manque d'interactivité, et il faudrait enlever le hover effect sur le graph

2020-11-23 11:18 UTC, Narcasung approved these changes

2020-11-23 11:26 UTC, KevinBacas approved these changes

2020-11-23 13:21 UTC, merged